services:
  - type: web
    name: jd-trading-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python jd_trading_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.8"
